spring.application.name=zgcmaster-fixture
spring.jmx.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoints.jmx.exposure.include=health,info,metrics
server.jetty.threads.max=16
server.jetty.threads.min=4
server.shutdown=graceful
